/**
 * Regenerate the ANTLR parser from src/grammar/TrinoSql.g4 and inject a
 * `@ts-nocheck` header (the generated code intentionally has unused
 * locals/params that would otherwise trip our strict tsconfig).
 *
 * Usage: node scripts/gen-parser.mjs   (or: npm run gen:parser)
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join } from "node:path";

const OUT = "src/generated";
const HEADER = "// @ts-nocheck — generated by ANTLR (antlr4ng), do not edit\n";

execFileSync(
  "npx",
  [
    "antlr4ng",
    "-Dlanguage=TypeScript",
    "-Xexact-output-dir",
    "-o",
    OUT,
    "src/grammar/TrinoSql.g4",
  ],
  { stdio: "inherit" },
);

for (const file of readdirSync(OUT)) {
  if (!file.endsWith(".ts")) continue;
  const path = join(OUT, file);
  const content = readFileSync(path, "utf8");
  if (!content.startsWith("// @ts-nocheck")) {
    writeFileSync(path, HEADER + content);
  }
}

console.log("Parser regenerated in", OUT);
